site_name: SugarRandom
copyright: Copyright &copy; 2021-2022 SugarRandom
theme:
  language: zh
  favicon: assets/logo.png
  name: material
  features:
    - navigation.tabs
  logo: assets/logo.png
repo_url: https://github.com/MikuSugar/SugarRandom
repo_name: MikuSugar/SugarRandom
site_description:  SugarRandom官方网站
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - 主页: index.md
  - 更新日志: log.md
  - 安装:
      - 简介: setup/index.md
  - WEB使用:
      - 快速使用: usage_web/index.md
      - 配置: usage_web/config.md
      - 生成代码: usage_web/generate_code.md
  - CLI使用:
      - 快速使用: usage_cli/quick_cli_new.md
      - 生成代码: usage_cli/generate_code.md
      - alias: usage_cli/alias.md
      - cat: usage_cli/cat.md
  - 随机类型:
      - 简介: randomtype/index.md
      - 表达式随机: randomtype/expression.md
      - 默认国内城市: randomtype/cncity.md
      - 随机范围的整数: randomtype/rangenumber.md
      - 指定列表的随机: randomtype/randomlist.md
      - 随机对象: randomtype/obj.md
      - 随机数组长度: randomtype/array.md
      - 随机中文姓名: randomtype/cnname.md
      - 随机邮箱: randomtype/email.md
      - 随机中国大陆手机号: randomtype/cnphone.md
      - 随机ipv4/ipv6: randomtype/ip.md
      - UUID: randomtype/uuid.md
      - MAC: randomtype/mac.md
      - 随机生成经纬度: randomtype/LONLAT.md
      - 随机生成浏览器代理: randomtype/user_agent.md
  - 开发:
      - 简介: develop/index.md
      - 新的随机类型: develop/newtype.md
      - 如何在自己的代码引用造数服务类: develop/import.md

