site_name: SugarRandom
copyright: Copyright &copy; 2021-2022 SugarRandom
theme:
  language: zh
  favicon: assets/logo.png
  name: material
  features:
    - navigation.tabs
  logo: assets/logo.png
repo_url: https://github.com/MikuSugar/SugarRandom
repo_name: MikuSugar/SugarRandom
site_description:  SugarRandom官方网站
nav:
  - 主页: index.md
  - 安装:
      - 简介: setup/index.md
  - WEB使用:
      - 快速使用: usage_web/index.md
      - 配置: usage_web/config.md
      - 生成代码: usage_web/generate_code.md
  - CLI使用:
      - 快速使用: usage_cli/quick_cli.md
      - 新版命令: usage_cli/quick_cli_new.md
      - 生成代码: usage_cli/generate_code.md
  - 开发:
      - 简介: develop/index.md
      - 新的随机类型: develop/newtype.md
