name: Deploy to Demo
on:
  workflow_run:
    workflows:
      - packages
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 登录到服务器拉取代码重新启动
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /root/soft/SugarRandom
            git pull
            cd sugar_random_core
            mvn install
            cd ../
            kill -9 $(lsof -t -sTCP:LISTEN -i:8080)
            mvn clean package -Pproduction
            nohup java -jar target/*.jar  > log.log &!
          host: ${{ secrets.DEPLOY_HOST }}
          user: root
          pass: ${{ secrets.DEPLOY_PASSWORD }}
          args: "-tt"